:navtitle: Queries
= Queries

This section describes the additional functionality attached to Axon's query dispatching and handling logic.

[[querygateway]]
== `QueryGateway`

Several inlined extension methods have been introduced on the `QueryGateway` to use generics instead of explicit `Class` parameters.

=== Single-result query

`query<R, Q>` dispatches a point query and returns a `CompletableFuture<R>`:

[source,kotlin]
----
import org.axonframework.extensions.kotlin.query
import org.axonframework.messaging.queryhandling.gateway.QueryGateway

class QueryDispatcher(private val queryGateway: QueryGateway) {

    fun getTotalNumberOfCards(): Int =
        queryGateway.query<Int, CountCardSummariesQuery>(CountCardSummariesQuery()).join()
}

data class CountCardSummariesQuery(val filter: String = "")
----

Kotlin's type inference can often deduce the types automatically from the return type context:

[source,kotlin]
----
import org.axonframework.extensions.kotlin.query
import org.axonframework.messaging.queryhandling.gateway.QueryGateway
import java.util.concurrent.CompletableFuture

class QueryDispatcher(private val queryGateway: QueryGateway) {

    fun getTotalNumberOfCards(): CompletableFuture<Int> =
        queryGateway.query(CountCardSummariesQuery())
}

data class CountCardSummariesQuery(val filter: String = "")
----

=== Multi-result query

`queryMany<R, Q>` dispatches a query expecting a list of results and returns a `CompletableFuture<List<R>>`:

[source,kotlin]
----
import org.axonframework.extensions.kotlin.queryMany
import org.axonframework.messaging.queryhandling.gateway.QueryGateway

class QueryDispatcher(private val queryGateway: QueryGateway) {

    fun findAllCards(): List<CardSummary> =
        queryGateway.queryMany<CardSummary, FindAllCardsQuery>(FindAllCardsQuery()).join()
}

class FindAllCardsQuery
data class CardSummary(val id: String)
----

=== Subscription query

`subscriptionQuery<R, Q>` opens a subscription query and returns a `Publisher<R>` of incremental updates:

[source,kotlin]
----
import org.axonframework.extensions.kotlin.subscriptionQuery
import org.axonframework.messaging.queryhandling.gateway.QueryGateway
import org.reactivestreams.Publisher

class QueryDispatcher(private val queryGateway: QueryGateway) {

    fun subscribeToCardUpdates(): Publisher<CountChangedUpdate> =
        queryGateway.subscriptionQuery<CountChangedUpdate, CountCardSummariesQuery>(CountCardSummariesQuery())
}

data class CountCardSummariesQuery(val filter: String = "")
class CountChangedUpdate
----

=== Streaming query

`streamingQuery<R, Q>` dispatches a streaming query and returns a `Publisher<R>` of result elements:

[source,kotlin]
----
import org.axonframework.extensions.kotlin.streamingQuery
import org.axonframework.messaging.queryhandling.gateway.QueryGateway
import org.reactivestreams.Publisher

class QueryDispatcher(private val queryGateway: QueryGateway) {

    fun streamAllCards(): Publisher<CardSummary> =
        queryGateway.streamingQuery<CardSummary, FindAllCardsQuery>(FindAllCardsQuery())
}

class FindAllCardsQuery
data class CardSummary(val id: String)
----

[[queryupdateemitter]]
== `QueryUpdateEmitter`

An inline `emit` extension method has been added to `QueryUpdateEmitter` to simplify calls by using generics and moving the lambda predicate to the end of the parameter list, enabling trailing-lambda syntax.

[source,kotlin]
----
import org.axonframework.extensions.kotlin.emit
import org.axonframework.messaging.queryhandling.QueryUpdateEmitter
import org.axonframework.eventhandling.EventHandler

class CardSummaryProjection(private val queryUpdateEmitter: QueryUpdateEmitter) {

    @EventHandler
    fun on(event: CardIssuedEvent) {
        // Update projection here

        // Then emit the CountChangedUpdate to subscribers of CountCardSummariesQuery
        // matching the given filter
        queryUpdateEmitter.emit<CountCardSummariesQuery, CountChangedUpdate>(CountChangedUpdate()) { query ->
            event.id.startsWith(query.idFilter)
        }
    }
}

class CardIssuedEvent(val id: String)
class CountChangedUpdate
data class CountCardSummariesQuery(val idFilter: String = "")
----
