name: Kotlin Extension

on:
  pull_request:

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: 8
            sonar-enabled: false
          - java-version: 11
            sonar-enabled: true
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache .m2
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Regular Build
        run: |
          ./mvnw -B -U clean verify

      - name: Sonar Analysis
        if: ${{ success() && matrix.sonar-enabled && github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          ./mvnw -B -Pcoverage sonar:sonar \
          -Dsonar.projectKey=AxonFramework_extension-kotlin \
          -Dsonar.organization=axonframework \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
